import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'


export default function Home() {
  return (
    <div className={styles.container}>
      <style>{`
      h2 {
        font-size : 32px;
      }
      h3 {
        font-size : 24px;
      }
      `}
      </style>
      {/* <Head>
        <title>Hunting Coder</title>
        <meta name="description" content="Generated by Muhammad Haris Ali" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}
      
      
      <main className={styles.main}>
        <div className={styles.hero_img} >

        <Image src="/developer.jpg" alt="developer" width={3200} height={1200}  />
        </div>
        <h1 className={styles.title}>
          {"<Welcome to Hunting Coder/>"}
        </h1>
        <p className={styles.description}>
          Get started with us
        </p>
         <div className="blogs">
          <h2>popular Blogs</h2>
          <div className="blogItem">
            <h3>How to learn javaScript in 2022</h3>
            <p>javascript is a language for the logic for the web</p>
          </div>
          <div className="blogItem">
            <h3>How to learn javaScript in 2022</h3>
            <p>javascript is a language for the logic for the web</p>
          </div>
          <div className="blogItem">
            <h3>How to learn javaScript in 2022</h3>
            <p>javascript is a language for the logic for the web</p>
          </div>
         </div>
     
      </main>

    
    </div>
  )
}
